### ISSUE TITLE
highlight gets off - chrome 80

### ISSUE THREAD

**Issue by MichaelChambers** [wooorm/write-music#9]
FYI - on initial load of the demo site, in Chrome 80, on Windows 8.1:
The highlight slipped to the wrong characters.
![image](https://user-images.githubusercontent.com/649078/77715416-edef5100-6fb1-11ea-934d-121210a382c4.png)

(I'm still just trying to figure out how your stuff works, as I wanted to use your readability. Neat stuff, but I probably won't be able to figure out why this is off.)

**Comment by MichaelChambers** [comment]
In Dev Tools, when I select .draw's harmony (3rd line above), Chrome's highlight for the selected word is from the "a" through the period. So the color highlighting is acting like there is an nbsp at the beginning of the line.

**Comment by wooorm** [comment]
Hmm, thanks for the issue!

This is probably some CSS setting that is set on the textarea by default in your browser, which isn’t included here:

https://github.com/wooorm/write-music/blob/b70fb74716080235e2cbfa44327d27c24bed499f/src/index.css#L111-L130

Unfortunately I don’t have access to Windows, and for me Safari, Firefox, Chrome, Chromium, and Chrome Canary all work fine, so I’m not sure how to solve this. If you’re interested, could you look into it?

**Comment by MichaelChambers** [comment]
I just checked Chrome Beta (81), and the sync is fine. It is also fine in Firefox. Happily, nothing to do but wait a bit!

**Comment by wooorm** [comment]
Thanks for checking, well that’s good! Shall I close this then?
